### ISSUE TITLE
Add implementation of - Fig 2.6 simple reflex agent

### ISSUE THREAD

**Issue by smsubham** [aimacode/aima-java#120]
Implementation of Figure 2.6 A simple reflex agent. It acts according to a rule whose condition matches the current
state, as defined by the precept.

**Comment by anurag-rai** [comment]
@smsubham May I know which edition of AIMA you are referring to? Or the page number? Because in the third one, Figure 2.6 lists "Examples of task environments and their characteristics.".

**Comment by ctjoreilly** [comment]
Closing until clarification received as to what this issue is actually related to.

**Comment by smsubham** [comment]
Actually I had some other edition of this book so issue referred to wrong fig no . sorry for the inconvenience. And can we add issue for adding algorithm not yet implement from this book? @ctjoreilly @anurag-rai

**Comment by ctjoreilly** [comment]
All outstanding algorithms for the 3rd edition of the book (i.e. AIMA3e) should already have outstanding issues for them. If you see one missing please open and I will review. Similarly, if a piece of functionality can be improved and an already existing issue does not exist its fine to submit.

Best

Ciaran
