### ISSUE TITLE
AIMA4e implement Fig 4.2 Hill Climbing from AIMA3e branch

### ISSUE THREAD

**Issue by appoll** [aimacode/aima-java#122]
Fig 4.2 Hill Climbing, page 122 in third edition. 
Issue needs AIMA4e label.

**Comment by appoll** [comment]
I guess issue is not needed, since the pull request created one itself.

**Comment by ctjoreilly** [comment]
I've been going back and forward between writing up explicit issues for each of the AIMA3e algorithms to be ported over to the AIMA4e branch. I think its probably a good idea just to make things more explicit. Perhaps a naming convention like: 'AMA4e rewrite of Fig 4.2 Hill Climbing from AIMA3e branch'. Feel free to enter. 

Thanks

Ciaran

**Comment by appoll** [comment]
to be closed by pull request https://github.com/aimacode/aima-java/pull/123
