### ISSUE TITLE
AIMA4e reimplement Fig 4.8 Genetic-Algorithm from AIMA3e branch

### ISSUE THREAD

**Issue by ctjoreilly** [aimacode/aima-java#129]

**Comment by anuj1995** [comment]
I would like to implement it

**Comment by ctjoreilly** [comment]
A pull request has already been submitted for this so your efforts will likely overlap.

**Comment by BenK10** [comment]
has it been accepted yet?

**Comment by ctjoreilly** [comment]
No, the pull request was closed by the submitter. The GA has recently been updated on the AIMA3e branch and I will be looking to migrate it over in the coming weeks. Currently reworking the search algorithms from chapters 3 and 4 that come before it. Once complete GA will be next to be migrated.
