### ISSUE TITLE
AIMA4e reimplement Fig 4.21 Online-DFS-Agent from AIMA3e branch

### ISSUE THREAD

**Issue by ctjoreilly** [aimacode/aima-java#132]

**Comment by appoll** [comment]
Hi, 
I had already started tackling this one in the past week but at the moment I am stuck at writing the tests. However, if anyone is willing to add on top of it, the branch is [here](https://github.com/appoll/aima-java/tree/AIMA4e-132). 
Cheers, 
Paul

**Comment by smsubham** [comment]
Hi Paul,
Ok let me try to write test cases for it.
Is implementation correct or do i need to work  on it too.
@appoll

**Comment by appoll** [comment]
Well I wouldn't call it correct until it's tested. From my perspective it is close to being complete and if some things are missing they should be spotted when running the tests.

**Comment by smsubham** [comment]
ok. Let me write test cases for it and try to get things right.
