### ISSUE TITLE
AIMA4e reimplement Fig 5.3 Minimax-Decision from AIMA3e branch

### ISSUE THREAD

**Issue by ctjoreilly** [aimacode/aima-java#134]

**Comment by tmt96** [comment]
I would like to work on this issue. Is this still open?

**Comment by ctjoreilly** [comment]
Yes.

**Comment by tmt96** [comment]
I gave the issue a try the last few days. [Here is the branch](https://github.com/MinhTuanTran/aima-java/tree/AIMA4e). Not many changes from what we have in AIMA3e though. I haven't written tests yet, so I hope to find some suggestions.

**Comment by mshubhankar** [comment]
Please create a pull request from your base branch,so that your implementation can be easily seen.
