### ISSUE TITLE
Add Implementation of Air-Cargo-problem Fig 10.1 for AIMA3e branch

### ISSUE THREAD

**Issue by smsubham** [aimacode/aima-java#217]
No implementation of this was found so added this issue.

**Comment by smsubham** [comment]
Have opened this issue and will be submitting a patch for it soon. @ctjoreilly

**Comment by anurag-rai** [comment]
Hi @smsubham , I'm not sure if this (like #218) requires an implementation... These cases can be modeled as Test Cases, perhaps, for (say) Search algorithms. Although, if this is an issue altogether would depend on @ctjoreilly

**Comment by smsubham** [comment]
Hi @anurag-rai
Good to hear from you. Am aware of this.
Actually yesterday i had an opportunity to have a look at [aima-python](https://github.com/aimacode/aima-python) page , found these fig no's (issues #217 #218 #219 #220 #221 ) in missing list of algorithms which are yet to be implemented in AIMA-Python. Have tagged @ctjoreilly sir in these issue comments , so that he can have a look at these issues and clarify if its required. But i think these issues should be accepted , most of these will be modeled as test cases though.

**Comment by anurag-rai** [comment]
Oh ok. Good to know the reference!

**Comment by divsidhu-26** [comment]
@ctjoreilly i would like to work on this isssue if it is still open.......

**Comment by ctjoreilly** [comment]
Yes.

**Comment by divsidhu-26** [comment]
@ctjoreilly can u give a little description how you want this code to be implemented......
Do i need to build a new parser or can i use the FOLParser directly?

**Comment by ctjoreilly** [comment]
You can likely get away with the FOL Parser if you use a simple pre-parser to break up the file into the specific sections (i.e. Action, PRECOND, and Effect sections). The FOL parser on the aima4e branch in the 'extra' module is better to use as it doesn;t require that you specify an FOLDomain manually beforehand (i.e. it automatically extracts predicates, constants and functions based on the parse).

Best

Ciaran

**Comment by samagra14** [comment]
This has already been implemented. Therefore closing this issue.
