### ISSUE TITLE
DepthFirstSearch and BreadthFirstSearch not work

### ISSUE THREAD

**Issue by garciacarmonaam** [aimacode/aima-java#222]
THIS ISSUE HAS BEEN DELETED BY ME. FINALLY, ANY HELP IS NECESSARY

**Comment by smsubham** [comment]
Hi
Thanks you for using AIMA-JAVA. Which version of library did you use?
@garciacarmonaam

**Comment by garciacarmonaam** [comment]
Hi!
I'm using this version: https://github.com/aimacode/aima-java/releases/tag/aima3e-v1.8.1.
Thanks

Ángel Manuel García CarmonaEstudiante de Ingeniería de SoftwareDesarrollador de quiLéxico
Avenida de la Constitución 38ºQuintana de la Serena (BA, ESP)+34634760756@GarciaCarmonaAM - www.amgarciac.es

Date: Fri, 15 Apr 2016 07:47:19 -0700

**Comment by smsubham** [comment]
Ok so you are using aima-java 3e branch codes. To use it did you write test cases or used some other way? 

@garciacarmonaam

**Comment by garciacarmonaam** [comment]
Yes, I did.

Ángel Manuel García Carmona
Estudiante de Ingeniería de Software
Desarrollador de quiLéxico

Avenida de la Constitución 38º
Quintana de la Serena (BA, ESP)
+34634760756
@GarciaCarmonaAM - www.amgarciac.es

**Comment by smsubham** [comment]
Can you please upload source code for your implementation in a text file. 
I would also suggest you to have a look at  [DepthFirstSearch](https://github.com/aimacode/aima-java/blob/AIMA3e/aima-core/src/test/java/aima/test/core/unit/search/uninformed/BreadthFirstSearchTest.java) and [BreadthFirstSearch ](https://github.com/aimacode/aima-java/blob/AIMA3e/aima-core/src/test/java/aima/test/core/unit/search/uninformed/DepthFirstSearchTest.java) to see how classes mentioned in issue are used in test cases.
@garciacarmonaam

**Comment by garciacarmonaam** [comment]
In 1 hour, I Will do that 

Ángel Manuel García Carmona
Estudiante de Ingeniería de Software
Desarrollador de quiLéxico

Avenida de la Constitución 38º
Quintana de la Serena (BA, ESP)
+34634760756
@GarciaCarmonaAM - www.amgarciac.es

**Comment by garciacarmonaam** [comment]
System.out.println("\n<------------------------>");		System.out.println("Profundidad (DFS (Graph))");		System.out.println("<------------------------>");		uninformedAndInformedSearchDemo(lightsout, LightsOutFunctionFactory.getActionsFunction(),					LightsOutFunctionFactory.getResultFunction(),					new LightsOutGoalTest(),new DepthFirstSearch(new GraphSearch()));						System.out.println("\n<------------------------>");		System.out.println("Anchura (BFS (Graph))");		System.out.println("<------------------------>");		lightsout= new LightsOut(LIGHTSOUT);		uninformedAndInformedSearchDemo(lightsout, LightsOutFunctionFactory.getActionsFunction(),					LightsOutFunctionFactory.getResultFunction(),					new LightsOutGoalTest(),new BreadthFirstSearch(new GraphSearch()));
------------
	private static void uninformedAndInformedSearchDemo(Object initialState,			ActionsFunction actionsFunction,ResultFunction resultFunction,			GoalTest goalTest,Search searchType) {		try {			Problem problem = new Problem(initialState,actionsFunction,resultFunction,goalTest);					Search search = searchType;			long timeI = System.currentTimeMillis();			SearchAgent agent = new SearchAgent(problem, search);			long timeF = System.currentTimeMillis();			printActions(agent.getActions());			printInstrumentation(agent.getInstrumentation());			printTimeExecution(timeI,timeF);			printGraphicActions(agent.getActions(),initialState);					} catch (Exception e) {			e.printStackTrace();		}	}
Ángel Manuel García CarmonaEstudiante de Ingeniería de SoftwareDesarrollador de quiLéxico
Avenida de la Constitución 38ºQuintana de la Serena (BA, ESP)+34634760756@GarciaCarmonaAM - www.amgarciac.es

Date: Fri, 15 Apr 2016 08:19:10 -0700

**Comment by smsubham** [comment]
Please upload complete code including import statement , class name and its functions.  
Include LightsOutFunctionFactory class source code , which is used here. Can u upload your code in notepad file?
@garciacarmonaam

**Comment by garciacarmonaam** [comment]
I cannot because it's for an academic task and I'm worried about the fact, another mate could share my code and I would not be able to pass the subject. I'd sent that to a private email.

Ángel Manuel García CarmonaEstudiante de Ingeniería de SoftwareDesarrollador de quiLéxico
Avenida de la Constitución 38ºQuintana de la Serena (BA, ESP)+34634760756@GarciaCarmonaAM - www.amgarciac.es

Date: Fri, 15 Apr 2016 09:25:16 -0700

**Comment by garciacarmonaam** [comment]
Hi! I have noticed about these methods (not all) does not test all cases.

Ángel Manuel García CarmonaEstudiante de Ingeniería de SoftwareDesarrollador de quiLéxico
Avenida de la Constitución 38ºQuintana de la Serena (BA, ESP)+34634760756@GarciaCarmonaAM - www.amgarciac.es

Date: Fri, 15 Apr 2016 09:25:16 -0700

**Comment by smsubham** [comment]
I share your concern. But it seems like you are asking me to solve your homework. In that case am not sure if i would be able to help you. But do drop a mail to me with  at smsubham342@gmail.com , with source code in .txt file. @garciacarmonaam 

Regards
Subham Mishra

**Comment by garciacarmonaam** [comment]
I will send you the email, but the idea is not the fact of doing my homework.

Ángel Manuel García Carmona
Estudiante de Ingeniería de Software
Desarrollador de quiLéxico

Avenida de la Constitución 38º
Quintana de la Serena (BA, ESP)
+34634760756
@GarciaCarmonaAM - www.amgarciac.es

**Comment by garciacarmonaam** [comment]
Finally, I am being helped by a cousin.
Thanks for all.Bye.

Ángel Manuel García CarmonaEstudiante de Ingeniería de SoftwareDesarrollador de quiLéxico
Avenida de la Constitución 38ºQuintana de la Serena (BA, ESP)+34634760756@GarciaCarmonaAM - www.amgarciac.es

Date: Fri, 15 Apr 2016 11:57:34 -0700

**Comment by smsubham** [comment]
Thank for being part of this community.

Best
Subham
