### ISSUE TITLE
Is there a guide on how to contribute?

### ISSUE THREAD

**Issue by hackthehackerman** [aimacode/aima-java#228]
Hello all. Thank you for your effort in working on this project. It is very helpful for students like me who would like to work through the examples. I am wondering if you welcome contribution and if there's a proper way for me to contribute to your effort in the 4e re-write? Thank you!

**Comment by anurag-rai** [comment]
https://github.com/aimacode/aima-java/commit/41a6d6e496099366657f443e4c851ccb83c2fb8f

**Comment by hackthehackerman** [comment]
Thank you. I have gotten into contact with him.
