### ISSUE TITLE
Use Generic type instance in place of datatype specific functions.

### ISSUE THREAD

**Issue by Manthan-R-Sheth** [aimacode/aima-java#247]
This is with reference to [Metrics.java](https://github.com/aimacode/aima-java/blob/AIMA3e/aima-core/src/main/java/aima/core/search/framework/Metrics.java) but can be implemented project wide.
Generic type instance can be used instead of functions for handling different datatypes.

**Comment by ctjoreilly** [comment]
This is a goal of the rewrite effort on the AIMA4e branch. This will not be applied to the AIMA3e branch.
