### ISSUE TITLE
AIMA4e improve BidirectionalSearch API to include fine grained action source details

### ISSUE THREAD

**Issue by ctjoreilly** [aimacode/aima-java#264]
Update the  BidirectionalSearch API to support something like this:

interface BidirectionalActions {

  List<A> fromInitialStatePart()
  List<A> fromGoalStatePart()
  List<A> fromInitialStateToGoalState(); // What I was indicating above I was expecting as  a result
  List<A> fromGoalStateToInitialState(); // essential the reverse of the previous method.

}

as the return from SearchForActionsBidirectionallyFunction and update the tests accordingly.

**Comment by Manthan-R-Sheth** [comment]
@ctjoreilly 
What is expected to be the output of ```fromInitialStatePart()``` and ```fromGoalStatePart()``` ?

**Comment by ctjoreilly** [comment]
`fromInitialStatePart()` would be the actions to go from the initial state to the point it met with the backward search.
`fromGoalStatePart()` would be the actions to go from the goal state to the point it met with the forward search.

i.e. the last action of each sequence should lead you to the same state where the forward and backward searches met.

**Comment by Manthan-R-Sheth** [comment]
@ctjoreilly is it good to be closed?
And with respect to the TODO list for AIMA4e can we have these changes :-
1. Add BidirectionalSearch Algorithm in the list of implemented algorithms.
2. Update the TODO list as well. 
3. For TODO of chapter 8, domain is already auto-populating while FOL parsing by the use of listeners. Please correct me if I am wrong here. If not, I would like to work on it.

**Comment by ctjoreilly** [comment]
Hi,

On Wed, Mar 22, 2017 at 11:33 AM, Manthan-R-Sheth <notifications@github.com>
wrote:

> @ctjoreilly <https://github.com/ctjoreilly> is it good to be closed?
> And with respect to the TODO list for AIMA4e can we have these changes :-
>
>    1. Add BidirectionalSearch Algorithm in the list of implemented
>    algorithms.
>
>
Done. Is now in the README.md list.

>
>    1. Update the TODO list as well.
>
>
Done.


>
>    1. For TODO of chapter 8, domain is already auto-populating while FOL
>    parsing by the use of listeners. Please correct me if I am wrong here. If
>    not, I would like to work on it.
>
>
Removed, the new parser does automatically populate the domain now (the
tests also verify this).

Thanks

Ciaran

**Comment by Manthan-R-Sheth** [comment]
Thanks.
