### ISSUE TITLE
aimax.osm.gps File named as Txt NmeaSerialPortReader.txt

### ISSUE THREAD

**Issue by zaynkorai** [aimacode/aima-java#276]
While Running Aimax-OSM class not found exception is occurring. File is saved as .txt file extension.

**Comment by ctjoreilly** [comment]
@RuedigerLunde could you look into this.

Thanks

Ciaran

**Comment by RuedigerLunde** [comment]
This is not a bug but a feature. The NmeaSerialPortReader class depends on additional (partly platform-specific) libraries as described in the class documentation. This solution (txt-extension) together with the reflection trick in the corresponding factory class avoids compile-time errors if the additional libraries are not available. So aimax-osm can be used without them. Users who want to use the localization feature just need to install the additional libraries, replace txt by java, and compile it.

Rüdiger
