### ISSUE TITLE
UniformCostQueueSearch<>(new GraphRLPriorityQueueSearch<>()) fails UniformCostSearchTest

### ISSUE THREAD

**Issue by ctjoreilly** [aimacode/aima-java#283]
Currently commented out in test case.

**Comment by Manthan-R-Sheth** [comment]
@ctjoreilly
The problem is that, node is never added to ```explored``` before the loop structure and its containment is checked in the while condition. Hence, being always true (```!explored.contains(node.state())```), all nodes from ```frontier``` are removed till the queue becomes empty and returns ```failure()```.
We need to find a method to populate ```explored``` and then execute the do...while loop.

**Comment by Manthan-R-Sheth** [comment]
```
...........
explored.add(node.state());
while (loopDo()) {
	// if EMPTY?(frontier) then return failure
	if (frontier.isEmpty())
		return failure();
	// node <- POP(frontier) /* chooses the highest priority node in
		// frontier */
	node = frontier.remove();
	// if problem.GOAL-TEST(node.STATE) then return SOLUTION(node)
	if (isGoalState(node, problem)) {
		return solution(node);
	}
	if (frontier.contains(node)) {
		while (frontier.contains(node))
			frontier.remove();
	}
        // add node.STATE to explored
	explored.add(node.state());
	// for each action in problem.ACTIONS(node.STATE) do
	for (A action : problem.actions(node.state())) {
		// child <- CHILD-NODE(problem, node, action)
		Node<A, S> child = newChildNode(problem, node, action);
		// if child.STATE is not in explored then
		if (!explored.contains(child.state())) {
			// frontier <- INSERT(child, frontier)
			frontier.add(child);
		}

	}
}
.............
```
This gives desired results and passes the test cases. Duplicate states are handled but it doesn't strictly adhere to the algorithm mentioned in the java doc, although it does the same thing.
On approval, I can make a PR.
@ctjoreilly

**Comment by ctjoreilly** [comment]
Its going to take me a couple of days before I can look at this in detail.
A bit swamped with reviewing GSoC draft proposals at the moment.

Thanks

Ciaran

**Comment by Manthan-R-Sheth** [comment]
@ctjoreilly 
Sure :+1:

**Comment by ctjoreilly** [comment]
I have fixed, just needed to change:

while (!explored.contains(node.state()));

to:

while (explored.contains(node.state()));

to match the description in the pseudocode, the 'not' in the description makes it a little confusing.

**Comment by Manthan-R-Sheth** [comment]
@ctjoreilly  if you could remove the ```not``` in the pseudocode and corresponding comment in ```GraphRLPriorityQueueSearch```. This will make the algorithm and comments synced with the code.

**Comment by ctjoreilly** [comment]
while (explored.contains(node.state()));
 is looping 'until node.STATE not in explored' so as it stands it is correct.
