### ISSUE TITLE
3.11	Breadth-First-Search.java

### ISSUE THREAD

**Issue by prasadwajekar** [aimacode/aima-java#301]
while executing the code getting the following set of errors:

 
Main.java:48: error: class BreadthFirstSearch is public, should be declared in a file named BreadthFirstSearch.java
public class BreadthFirstSearch implements SearchForActions, SearchForStates {
       ^
Main.java:5: error: package aima.core.agent does not exist
import aima.core.agent.Action;
                      ^
Main.java:6: error: package aima.core.search.framework does not exist
import aima.core.search.framework.Metrics;
                                 ^
Main.java:7: error: package aima.core.search.framework does not exist
import aima.core.search.framework.Node;
                                 ^
Main.java:8: error: package aima.core.search.framework does not exist
import aima.core.search.framework.NodeExpander;
                                 ^
Main.java:9: error: package aima.core.search.framework does not exist
import aima.core.search.framework.QueueFactory;
                                 ^
Main.java:10: error: package aima.core.search.framework does not exist
import aima.core.search.framework.SearchForActions;
                                 ^
Main.java:11: error: package aima.core.search.framework does not exist
import aima.core.search.framework.SearchForStates;
                                 ^
Main.java:12: error: package aima.core.search.framework does not exist
import aima.core.search.framework.SearchUtils;
                                 ^
Main.java:13: error: package aima.core.search.framework.problem does not exist
import aima.core.search.framework.problem.Problem;
                                         ^
Main.java:14: error: package aima.core.search.framework.qsearch does not exist
import aima.core.search.framework.qsearch.GraphSearch;
                                         ^
Main.java:15: error: package aima.core.search.framework.qsearch does not exist
import aima.core.search.framework.qsearch.QueueSearch;
                                         ^
Main.java:48: error: cannot find symbol
public class BreadthFirstSearch implements SearchForActions, SearchForStates {
                                           ^
  symbol: class SearchForActions
Main.java:48: error: cannot find symbol
public class BreadthFirstSearch implements SearchForActions, SearchForStates {
                                                             ^
  symbol: class SearchForStates
Main.java:50: error: cannot find symbol
	private final QueueSearch implementation;
	              ^
  symbol:   class QueueSearch
  location: class BreadthFirstSearch
Main.java:56: error: cannot find symbol
	public BreadthFirstSearch(QueueSearch impl) {
	                          ^
  symbol:   class QueueSearch
  location: class BreadthFirstSearch
Main.java:64: error: cannot find symbol
	public List<Action> findActions(Problem p) {
	                                ^
  symbol:   class Problem
  location: class BreadthFirstSearch
Main.java:64: error: cannot find symbol
	public List<Action> findActions(Problem p) {
	            ^
  symbol:   class Action
  location: class BreadthFirstSearch
Main.java:71: error: cannot find symbol
	public Object findState(Problem p) {
	                        ^
  symbol:   class Problem
  location: class BreadthFirstSearch
Main.java:78: error: cannot find symbol
	public NodeExpander getNodeExpander() {
	       ^
  symbol:   class NodeExpander
  location: class BreadthFirstSearch
Main.java:83: error: cannot find symbol
	public Metrics getMetrics() {
	       ^
  symbol:   class Metrics
  location: class BreadthFirstSearch
Main.java:53: error: cannot find symbol
		this(new GraphSearch());
		         ^
  symbol:   class GraphSearch
  location: class BreadthFirstSearch
Main.java:63: error: method does not override or implement a method from a supertype
	@Override
	^
Main.java:66: error: cannot find symbol
		Node node = implementation.findNode(p, QueueFactory.<Node>createFifoQueue());
		^
  symbol:   class Node
  location: class BreadthFirstSearch
Main.java:66: error: cannot find symbol
		Node node = implementation.findNode(p, QueueFactory.<Node>createFifoQueue());
		                                                     ^
  symbol:   class Node
  location: class BreadthFirstSearch
Main.java:66: error: cannot find symbol
		Node node = implementation.findNode(p, QueueFactory.<Node>createFifoQueue());
		                                       ^
  symbol:   variable QueueFactory
  location: class BreadthFirstSearch
Main.java:67: error: cannot find symbol
		return node == null ? SearchUtils.failure() : SearchUtils.getSequenceOfActions(node);
		                      ^
  symbol:   variable SearchUtils
  location: class BreadthFirstSearch
Main.java:67: error: cannot find symbol
		return node == null ? SearchUtils.failure() : SearchUtils.getSequenceOfActions(node);
		                                              ^
  symbol:   variable SearchUtils
  location: class BreadthFirstSearch
Main.java:70: error: method does not override or implement a method from a supertype
	@Override
	^
Main.java:73: error: cannot find symbol
		Node node = implementation.findNode(p, QueueFactory.<Node>createFifoQueue());
		^
  symbol:   class Node
  location: class BreadthFirstSearch
Main.java:73: error: cannot find symbol
		Node node = implementation.findNode(p, QueueFactory.<Node>createFifoQueue());
		                                                     ^
  symbol:   class Node
  location: class BreadthFirstSearch
Main.java:73: error: cannot find symbol
		Node node = implementation.findNode(p, QueueFactory.<Node>createFifoQueue());
		                                       ^
  symbol:   variable QueueFactory
  location: class BreadthFirstSearch
Main.java:77: error: method does not override or implement a method from a supertype
	@Override
	^
Main.java:82: error: method does not override or implement a method from a supertype
	@Override
	^
34 errors

**Comment by ctjoreilly** [comment]
The project compiles and passes all tests. Please review the wiki pages for how to setup.
