### ISSUE TITLE
[aima-gui] N-Queens Search App incorrect output

### ISSUE THREAD

**Issue by aayush26** [aimacode/aima-java#320]
**N-Queens Search App**
Inputs:
```
strategy = Hill Climbing
boardSize = 8
initConfig = FirstRow
```

Output:  
The first row is incorrect even after the strategy is finished computing. Is this the expected behavior?
![aimaguiissue](https://user-images.githubusercontent.com/11179568/27407269-555c7c88-56f5-11e7-9273-55622f7e07d2.png)

Another Input set:
```
strategy = Hill Climbing
boardSize = 8
initConfig = Random
```
Output:  
In case of initConfig = Random, sometimes the strategy correctly solves the N-Queen problem and sometimes it fails to do so.
1. The failed screenshot
![aimaguiinitrandom](https://user-images.githubusercontent.com/11179568/27407323-78f000ac-56f5-11e7-89ed-e935f0923688.png)
2. The successfully solved N Queen screenshot
![aimaguicorrent](https://user-images.githubusercontent.com/11179568/27407326-7e0ec1b8-56f5-11e7-8cf0-130a8fe75e2f.png)

**Comment by RuedigerLunde** [comment]
Yes, this is the expected behavior. Hill Climbing is (as all other local search algorithms) incomplete. It tries to find a goal state by moving upwards but can get stuck in a local maximum.

Best regards,
Rüdiger
