### ISSUE TITLE
forEach loop implementation

### ISSUE THREAD

**Issue by HasinduGajanayake** [aimacode/aima-java#324]
I think that the implementation of for each loop is erroneous in,
`aima-core/source/main/java/aima-core/environment/nlp/parsing/ProbUnrestrictedGrammer`
![foreach](https://user-images.githubusercontent.com/25544629/27807411-39a24078-605e-11e7-8afc-705f4c82fa12.png)
``

**Comment by HasinduGajanayake** [comment]
I will fix the issue

**Comment by RuedigerLunde** [comment]
What do you think is wrong with the current implementation?

**Comment by coderop2** [comment]
@HasinduGajanayake are u still working on the issue or can i try and fix it..?
