### ISSUE TITLE
Issue in the Documentation in building the project on intellij

### ISSUE THREAD

**Issue by HasinduGajanayake** [aimacode/aima-java#326]
I was not able to build the file  using the readme..and i found that maven dependancies also should attached.Unless the project builds with errors.

**Comment by HasinduGajanayake** [comment]
The solution is after doing steps according to the manual.Then right click in the pom.xml and click "Add as Maven Project".Now its OK .My classes are compiling.
![capture](https://user-images.githubusercontent.com/25544629/28540357-b5b89ade-70d2-11e7-99ae-68fda6ebf5b3.PNG)

**Comment by samagra14** [comment]
There is specifically no issue with the documentation. It works fine. I am closing this for now. Please feel free to reopen if there are still issues.
