### ISSUE TITLE
WumpusKnowledgeBase  

### ISSUE THREAD

**Issue by kaizokun** [aimacode/aima-java#339]
There is a little error inside tellTemporalPhysicsSentences method line 344

        for (int x = 1; x <= caveXDimension; x++) {
            for (int y = 1; y <= caveYDimension; y++) {
                tellSuccessorStateLocationAxiom(t, x, y);
                // Optimization to make questions about unvisited locations faster
                tell(new ComplexSentence(
                        newSymbol(LOCATION, t + 1, x, y),
                        Connective.IMPLICATION,
                        newSymbol(LOCATION_VISITED, x, y)));
            }
            tellSuccessorStateOrientationAxioms(t);
        }

tellSuccessorStateOrientationAxioms(t) is inside de loop but it not necessary. Anyway the sentences are added one time in the KB ...

**Comment by RuedigerLunde** [comment]
Should be fixed now. Thank you!
