### ISSUE TITLE
Are page numbers mentioned in the README consistent with the corresponding algorithm(s)/image(s) in the book?

### ISSUE THREAD

**Issue by abhi-jha** [aimacode/aima-java#347]

**Comment by utsavoza** [comment]
Yes, they serve as an index of the implemented algorithms. So I suppose they intend to remain consistent with the corresponding algorithms/images given in the book. Feel free to send a PR if you find it otherwise.

**Comment by abhi-jha** [comment]
They don't look consistent as per the book. I have the 3rd edition and I couldn't find corresponding image(s)/algorithm(s) in the book, at least not on the page number mentioned in the README. Most of the times it is 1-2 pages after what is mentioned in the README and images' numbering is also not consistent. For example there's no image named 2.

**Comment by utsavoza** [comment]
If I am not wrong the index not only depicts the pseudocode/algorithms/diagrams given in the book but also relevant abstractions that facilitates the implementation and enhances their comprehension.

**Comment by coderop2** [comment]
So is anyone correcting those page numbers..?

**Comment by samagra14** [comment]
@coderop2 The page numbers are as per the International edition of the book. You must be having some other edition and hence the difference. For instance, I possess the Indian subcontinent edition and this edition differs from the international one by almost 12 pages. Please check the international edition and feel free to open this issue again if the page numbers differ from the international edition.
