### ISSUE TITLE
Add implementation of - Fig 11.5  Hierarchical-Search

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aimacode/aima-java#35]
```
Fig 11.5  Hierarchical-Search.


```

Original issue reported on code.google.com by `ctjoreilly@gmail.com` on 23 Oct 2009 at 2:47

**Comment by mshubhankar** [comment]
I have written a code for hierarchical search and also given its output in another file. The inputs are for now given as CLI string inputs for testing the program.

**Comment by ctjoreilly** [comment]
Hi, when you have written unit tests for your code and are happy with how everything works please submit a pull request and I will review in detail.

Thanks

**Comment by mshubhankar** [comment]
Actually, i have just tried to implement the algroithm and made the input menu driven by the user from the console.

**Comment by mshubhankar** [comment]
This program takes input from problem.txt and input.txt which can be used as test case files.

**Comment by ctjoreilly** [comment]
Ok,

But I still require a JUnit set of tests so testing can be automated. Can you also submit your proposed additions/changes via a push request (I will not be pulling in files individually from people). Also, look at how other code in the project is structured and commented. All submissions should follow a similar style.

Thanks

**Comment by smsubham** [comment]
Tried to implement - Fig 11.5 Hierarchical-Search issue #35 . But on submission it says all test failed and no environment variables set. Please provide feedback so so that i can improve my code and better serve the community.

**Comment by mshubhankar** [comment]
I am not able to find the REFINEMENT function . Is it written in the search framework ? or do i have to explicitely define it.

**Comment by mshubhankar** [comment]
The algorithm contains a line APPEND(prefix,sequence,suffix), where all 3 of them are Actions. Could you please help me write this ?

**Comment by smsubham** [comment]
Would it be ok if i try to implement last 2 lines of Pseudo Code i.e.
else for each sequence in REFINEMENTS(hla, outcome, hierarchy) do
frontier ← INSERT(APPEND(prefix , sequence, suffix), frontier)
in some other format.

**Comment by samagra14** [comment]
This was resolved in #411. Hence, closing the issue.
