### ISSUE TITLE
Unlike aima-python, index of algorithms in aima-java does not mention whether any unit tests have been written for a specific algorithm.

### ISSUE THREAD

**Issue by hriaz17** [aimacode/aima-java#353]
This may make it difficult for beginners to know which algorithm has been tested and which hasn't been tested.  I would like to fix this in the documentation. Shall I go ahead?

**Comment by hriaz17** [comment]
This is the difference in documentation I'm talking about:
aima-java:
![image](https://user-images.githubusercontent.com/26842494/36933610-ddb67018-1efd-11e8-9b7f-6da43c4955cf.png)
aima-python:
![image](https://user-images.githubusercontent.com/26842494/36933630-38b1d93a-1efe-11e8-90f8-9b85159e24c7.png)

**Comment by samagra14** [comment]
This will surely be a better index. Feel free to send a PR. Also, the mentors have suggested looking for alternatives to the Ipython notebooks for java. It would be great to have such an index.

**Comment by samagra14** [comment]
Tests and notebook sections have been added. Hence I am closing this issue.
