### ISSUE TITLE
Implement HillClimbingSearchWithSidewaysMoves in AIMA3e

### ISSUE THREAD

**Issue by ritwik12** [aimacode/aima-java#357]
I noticed that HillClimbingSearchWithSidewaysMoves.java is present in AIMA4e branch but not in AIMA3e branch. I am sending a PR for the same.

**Comment by samagra14** [comment]
I am closing this issue as this issue is no longer required. See #358 for the discussion.

**Comment by ritwik12** [comment]
sure
