### ISSUE TITLE
Vectorization of aima.core.learning.neural code

### ISSUE THREAD

**Issue by SayaliPatkar** [aimacode/aima-java#387]
Currently, the code is hardwired to work with a neural network with a single hidden layer. Complete vectorization of code is possible where the user can specify the number of hidden layers + hidden units. and forward and backpropagation can run in the loop according to user-specified layer + unit values.  If mentors approve, I would like to work on it.

**Comment by ritwik12** [comment]
@SayaliPatkar I think you should include this in your proposal.
