### ISSUE TITLE
FirstOrderVisitor.java in package aima.extra.logic.firstorder.parser missing implementation dependent classes

### ISSUE THREAD

**Issue by hriaz17** [aimacode/aima-java#388]
![image](https://user-images.githubusercontent.com/26842494/37845312-fd4ee556-2eeb-11e8-91fa-2e03eb0a3047.png)

As you can see, FirstOrderVisitor.java requires several missing classes to be implemented in aima-4e, hence it is throwing up errors when running unit tests as well.  Should I copy over implementations from aima-3e to make it work @utsavoza @ctjoreilly @norvig?

**Comment by utsavoza** [comment]
@harisriaz17 The `FirstOrderParser` and `PropositionalLogicParser` are generated from their respective ANTLR grammar files when you build the project, or `extra` gradle module. I suppose in Eclipse IDE, you need to manually 'refresh the gradle project' after the build inorder for these changes to get reflected in the IDE.

**Comment by hriaz17** [comment]
Alright - thanks for your help! I got those files generated. Since you're here, can you please review this PR for me?
I wrote a couple of basic unit tests for the activation and derivative function used in neural networks (forward and back prop). 
https://github.com/aimacode/aima-java/pull/368

**Comment by samagra14** [comment]
This issue seems to have been resolved. Therefore I am closing this issue.
