### ISSUE TITLE
ClassicalSearch Notebook

### ISSUE THREAD

**Issue by samagra14** [aimacode/aima-java#423]
The following things need to be added to the classical search notebook:- 
* Examples demonstrating the use of all uninformed search algorithms from the book in solving the Romania Map problem.
* A detailed analysis(including time measurements) of the 8 puzzle problem by using various heuristics in the search.
* Reproduce an experiment similar to Fig 3.13 .

**Comment by jsuyash1514** [comment]
@samagra14 
I would like to work on this issue.

**Comment by samagra14** [comment]
Cool @jsuyash1514. Go ahead :smiley:

**Comment by samagra14** [comment]
The notebook looks complete.
