### ISSUE TITLE
Add implementation of - Fig 18.8  Cross-Validation-Wrapper

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aimacode/aima-java#43]
```
Fig 18.4  Cross-Validation-Wrapper


```

Original issue reported on code.google.com by `ctjoreilly@gmail.com` on 23 Oct 2009 at 3:03

**Comment by AdrianBZG** [comment]
Hi, I would like to work on this issue, and I have a question regarding the pseudocode. In CROSS-VALIDATION function, the hypothesis variable 'h' is assigned to a Learner with the parameter size, if I understand correctly, in the case of a decision tree learner, the size of the tree determines the number of nodes in it, so, just to have a clear idea of this, my question is:

- Having a decision tree learner with size = 2, means having a decision tree with depth of 2, having in this case, 2 attributes only, e.g., by taking a look at the book: Patrons and Hungry?

![dt1](https://user-images.githubusercontent.com/8275330/36201254-af12ffb4-117f-11e8-9f10-fd46b6e606a8.png)

Thanks!

**Comment by samagra14** [comment]
This issue was resolved in #408. Therefore closing this issue.
