### ISSUE TITLE
CSP Notebook

### ISSUE THREAD

**Issue by RohanBh** [aimacode/aima-java#434]
Currently, this project doesn't contain any notebook that illustrates the use of the code in the [csp package][1]. I'd like to add a notebook for the same purpose. Can I proceed?

[1]: https://github.com/aimacode/aima-java/tree/AIMA3e/aima-core/src/main/java/aima/core/search/csp

**Comment by samagra14** [comment]
Yeah Sure!! A lot of contributions are required for writing notebooks. You may proceed with the csp package. Just remember to give the chapter name to the jupyter notebook.

**Comment by RohanBh** [comment]
I apologize for this huge delay but I am busy as this is the internship season for my college. If anyone wants to claim this issue, they can.
