### ISSUE TITLE
Add Binder support for Java Notebooks

### ISSUE THREAD

**Issue by RohanBh** [aimacode/aima-java#435]
It will be of great utility if the students or other users of this project can directly access the code and notebooks without cloning the repo and setting up Jupyter locally on their machines.

This can be achieved by [Binder][1]. This is also currently being used in Dr. Norvig's [Pytudes][2].

[1]: https://mybinder.org/
[2]: https://github.com/norvig/pytudes

**Comment by samagra14** [comment]
Yes, it's a great idea. I will look into the details and technicalities and try to add it as soon as possible.
