### ISSUE TITLE
How can i get number of backtracking points?

### ISSUE THREAD

**Issue by ThuriyaThwin** [aimacode/aima-java#456]
I am facing difficulties in counting number of backtracking points in BacktrackingStrategy.java code.
How can I modify the code to get actual number of backtracking points.

**Comment by DuyTrieu1999** [comment]
Hi! Is this issue still open? Can I work on it?

**Comment by ThuriyaThwin** [comment]
Yes,fri .If you interest in CSP,please help me in Backjumping algorithm.
