### ISSUE TITLE
Add implementation of - Fig 25.9  Monte-Carlo-Localization

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aimacode/aima-java#50]
```
Fig 25.7  Monte-Carlo-Localization


```

Original issue reported on code.google.com by `ctjoreilly@gmail.com` on 23 Oct 2009 at 3:12

**Comment by spidey12** [comment]
@ctjoreilly can you please explain me what is meant by raycast and what does it return and is p(X'/X,v,w) and p(z/z_) are vectors ?? what is p(X0) and from do we get this value and how do we get p(zj/z_)
