### ISSUE TITLE
Update implementation of - Fig 9.6 FOL-BC-ASK

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aimacode/aima-java#51]
```
Fig  9.6  FOL-BC-ASK  (update to more closely map to AIMA3e)


```

Original issue reported on code.google.com by `ctjoreilly@gmail.com` on 28 Nov 2009 at 12:57

**Comment by ritwik12** [comment]
#395 updates only the Java doc. The implementation is not according to AIMA3e. It needs to be updated or reimplemented.

**Comment by samagra14** [comment]
#410 solves this issue. Therefore, closing this issue.
