### ISSUE TITLE
Provide alternative implementations of search algorithms that more closely correspond to pseudocode in book

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aimacode/aima-java#64]
```
The following algorithm implementations:

- figure 3.7 TreeSearch
- figure 3.7 GraphSearch
- figure 3.11 BreadthFirstSearch
- figure 3.14 UniformCostSearch
- figure 3.17 DepthLimitedSearch
- figure 3.18 IterativeDeepeningSearch
- figure 3.26 RecursiveBestFirstSearch

do not correspond closely to the pseudo code in the book (due to using several 
abstractions to make generally useful). To aid in understanding create 
additional non-general versions of these that more closely reflect the code in 
the book.


```

Original issue reported on code.google.com by `ctjoreilly@gmail.com` on 15 Jun 2011 at 12:38

**Comment by davidemdot** [comment]
Hello, I've seen that these algorithms are already enhanced on the AIMA4e branch. Is this issue closed?

Thanks.

**Comment by ctjoreilly** [comment]
Not yet. I want to wait till the algorithms from chapters 4 to 6 are also complete to ensure that all the search related algorithms work well together.

**Comment by ctjoreilly** [comment]
Base implementations of algorithms should now follow the pseudocode in the book more close (aima4e branch).
