### ISSUE TITLE
Make some classes Generics enabled

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aimacode/aima-java#67]
```
Hello, 

this is just a small comment on some classes and a request for making them use 
java Generics.

Why wouldn't you make some classes like Problem, ActionsFunction, 
ResultFunction generics enabled? Is there a specific reason for not doing so 
until now? 

thank you in advance,
Asterios
```

Original issue reported on code.google.com by `asteri...@gmail.com` on 10 Jul 2011 at 11:35

**Comment by HisDewness** [comment]
Hello!

I'm very interested in attempting to converting some classes using Generics for the Google SoC2016,
and I'd like to know what the next step is for going through with this process.

Any help is appreciated!

Ismail A.

**Comment by ctjoreilly** [comment]
I would focus efforts on the AIMA4e branch. Look at the existing rewrites of the search algorithms to get an idea of how this is being done (Note these are not finalized yet). The AIMA4e branch is still in its early stages so there is plenty of room to carve out a section of interest.

**Comment by smsubham** [comment]
Have tried to add generics support to existing implementation for AIMA4e branch in pull request #225 #216  #213. @ctjoreilly sir  @GoogleCodeExporter

**Comment by ctjoreilly** [comment]
All search apis in AIMA4e branch use generics.
