### ISSUE TITLE
AIMA4e Add generics to search framework

### ISSUE THREAD

**Issue by moshewe** [aimacode/aima-java#89]
Classes such as HeuristicFunction don't take Generics params and so extending them is clumsy. These classes can easily be genericized for better readability and decrease in RuntimeException-s.

**Comment by ctjoreilly** [comment]
The search framework is currently being rewritten under the AIMA4e branch:

https://github.com/aima-java/aima-java/tree/AIMA4e

lack of generics and several other usability issues are the motivation behind this rewrite. Any feedback on new approach appreciated.

**Comment by ctjoreilly** [comment]
Search framework has been rewritten on AIMA4e branch. Generics used along with closer correspondence to the pseudo-code in the book adhered to.
