### ISSUE TITLE
What to do the aima implementations in other languages

### ISSUE THREAD

**Issue by gideonite** [aimacode/aima-java#92]
Hi,

I've found implementations in python and lisp that are still hosted on Google Code. Shall we export them? e.g. http://code.google.com/p/aima-python/

Wouldn't it be nice if they were all under the same organization? Is it possible to change the name from aimi-java to aimi?

Thanks,
Gideon.

**Comment by ctjoreilly** [comment]
Hi Gideon,

I believe all those projects are under the MIT license so you can freely export to GitHub if you like. As regards a central organization on GitHub for all aima book language implementations I think its a nice idea but that it is a call to be made by the books authors and if possible the original owners of the projects under consideration for inclusion. 

The aima-java organization was set up originally to convey that work on the project was done by more than 1 individual, i.e. the person who exported it from Google code, which in this case was myself. However, Ravi Mohan, original creator/author of aima-java, and Ruediger Lunde have contributed huge chunks of the source base and deserve acknowledgements for their efforts too. 

Best 

Ciaran

**Comment by ctjoreilly** [comment]
New organization, 'aimacode', has been setup and currently includes aima-java and aima-python.
